
export const MAKE_RESERVATION_REQUEST = 'MAKE_RESERVATION_REQUEST';
export const MAKE_RESERVATION_ERROR = 'MAKE_RESERVATION_ERROR';

export const GET_USER_RESERVATIONS_REQUEST = 'GET_USER_RESERVATIONS_REQUEST';
export const GET_USER_RESERVATIONS_ERROR = 'GET_USER_RESERVATIONS_ERROR';

export const DELETE_RESERVATION_REQUEST = 'DELETE_RESERVATION_REQUEST';
export const DELETE_RESERVATION_ERROR = 'DELETE_RESERVATION_ERROR';
