export const GET_SHOW_TIMES_BY_MOVIE_ID_REQUEST = "GET_SHOW_TIMES_BY_MOVIE_ID_REQUEST";
export const GET_SHOW_TIMES_BY_MOVIE_ID_ERROR = "GET_SHOW_TIMES_BY_MOVIE_ID_ERROR";

export const GET_SHOW_TIME_REQUEST = "GET_SHOW_TIME_REQUEST"
export const GET_SHOW_TIME_ERROR = "GET_SHOW_TIME_ERROR"