services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cinemaData'
      - 'POSTGRES_PASSWORD=netlab'
      - 'POSTGRES_USER=postgres'
    container_name: 'cinemaDatabase'
    ports:
      - '5432:5432'
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge
